import { Serie } from './serie.js';
export var series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad", "https://as01.epimg.net/meristation/imagenes/2022/07/28/noticias/1659031135_880382_1659031165_noticia_normal.jpg"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311", "https://upload.wikimedia.org/wikipedia/en/1/1f/Orange_is_the_new_black_season_6.jpg"),
    new Serie(3, "Game of Thrones", "HBO", 7, "American fantasy drama", "https://www.hbo.com/game-of-thrones", "https://static.hbo.com/game-of-thrones-1-1920x1080.jpg"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, Leonard and Penny have finally gotten married. Even Sheldon has found a female companion, entering into a relationship agreement with neurobiologist Amy Farrah Fowler, and he recently took their relationship to the next level by marrying her after a long courtship. In their free time, Leonard and Sheldon enjoy fantasy role-playing games with their ever-expanding universe of friends, including fellow scientists Koothrappali, Wolowitz, and Wolowitz’s adorable microbiologist wife, Bernadette, who is adjusting to life with their two children.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://static.wikia.nocookie.net/doblaje/images/0/06/La_teor%C3%ADa_del_Big_Bang.jpg/revision/latest/top-crop/width/360/height/450?cb=20220214011226&path-prefix=es"),
    new Serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "https://www.bbc.co.uk/programmes/b018ttws", "https://flxt.tmsimg.com/assets/p8992561_b_h9_aa.jpg"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://images.immediate.co.uk/production/volatile/sites/3/2017/10/14337742-low_res-a-very-english-scandal-cba797b.jpg?quality=90&resize=620,413"),
    new Serie(7, "The Simpsons", "Fox", 40, "Stories of Springfield centered around The Simpsons, a not so normal american family", "https://www.foxtv.es/series/fox/los-simpson", "https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Simpsons_FamilyPicture.png/250px-Simpsons_FamilyPicture.png"),
    new Serie(8, "The Boys", "Amazon Video", 3, "The Boys shows the bad side of the good guys and how their power would corrupt them in a real world", "https://www.primevideo.com/detail/The-Boys/0KRGHGZCHKS920ZQGY5LBRF7MA?_encoding=UTF8&language=es_ES", "https://www.rockandpop.cl/wp-content/uploads/2021/06/the-boys-1.jpg"),
    new Serie(9, "Lost", "ABC", 6, "A mistery filled drama series where flight 815 crashes on a deserted island and the survivors have to find the way to adapt and save their lives", "https://www.starplus.com/es-419/series/lost/49VjIYAiy7oh", "https://i.blogs.es/c4ae5d/lost_logo/450_1000.jpg"),
    new Serie(10, "The Walking Dead", "AMC", 11, "Rick wakes up in an hospital following and accident and finds himself in a zombie apocalypse", "https://www.foxtv.es/series/fox/the-walking-dead", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/twd-primera-temporada-1575400170.jpg"),
];
